# DOS Safar Configuration for Anbernic Gaming Handhelds
# تكوين DOS Safar المحسن لأجهزة Anbernic المحمولة للألعاب

[system]
device_type = "anbernic"
log_level = "info"
config_persist_path = "/boot/dos_safar/"
enable_gpio = true
enable_battery_monitoring = true

[hardware]
test_timeout_seconds = 15           # Shorter timeout for handhelds
display_test_enabled = true
input_test_enabled = true
network_test_enabled = true
auto_save_working_config = true

# Anbernic specific hardware settings
[hardware.anbernic]
model_detection = "auto"            # auto, rg351p, rg351m, rg351v, rg552, rg35xx
screen_rotation = 0                 # Screen rotation: 0, 90, 180, 270
brightness_control = true           # Enable brightness control
power_management = "aggressive"     # conservative, balanced, aggressive
cpu_governor = "ondemand"           # CPU scaling for battery life
gpu_performance = "balanced"        # low, balanced, high
thermal_throttling = true           # Enable thermal protection
suspend_on_lid_close = true         # Suspend when closing (if applicable)

[network]
# WiFi settings optimized for gaming handhelds
wifi_ssid = "A7rf"                  # ← ضع اسم شبكتك هنا
wifi_password = "11111111aA"        # ← ضع كلمة المرور هنا
connection_timeout_seconds = 8      # Slightly longer for handhelds
auto_connect = true
ethernet_preferred = false          # WiFi preferred on handhelds

# Gaming handheld network optimizations
[network.gaming]
wifi_power_save = true              # Enable power saving for battery
low_latency_mode = false            # Disable for battery life
background_scanning = false         # Reduce background WiFi scanning
reconnect_on_resume = true          # Auto-reconnect after sleep
connection_quality_threshold = -70  # Minimum signal strength (dBm)

# Backup WiFi networks for gaming sessions
[[network.backup_networks]]
ssid = "YourPhoneHotspot"
password = "hotspot123"

[[network.backup_networks]]
ssid = "GamingWiFi"
password = ""

[[network.backup_networks]]
ssid = "PublicWiFi"
password = ""

# Network behavior optimized for handheld use
auto_scan_open_networks = true
prefer_saved_networks = true
max_connection_attempts = 2         # Fewer attempts to save battery

[web]
port = 8080
host = "0.0.0.0"
enable_cors = true
static_files_path = "assets/web"
auto_launch_interface = true
show_qr_code = true

# Gaming handheld web interface optimizations
[web.gaming]
mobile_optimized = true             # Mobile-first interface
touch_friendly = true               # Large touch targets
low_bandwidth_mode = true           # Optimize for slower connections
cache_aggressive = true             # Aggressive caching for performance
max_connections = 10                # Lower connection limit
session_timeout = 1800              # 30 minute session timeout

[boot]
menu_timeout_seconds = 2            # Faster timeout for gaming
default_os = ""
show_advanced_options = true        # Show gaming options
gaming_mode = true                  # Enable full gaming mode
auto_web_on_timeout = true
keyboard_interrupt_enabled = true
show_ip_on_screen = true

# Gaming handheld boot optimizations
[boot.gaming]
fast_boot = true                    # Ultra-fast boot for gaming
skip_hardware_tests = false         # Still test gaming controls
show_battery_status = true          # Show battery on boot screen
show_performance_mode = true        # Show current performance mode
boot_logo = "anbernic"              # Custom boot logo
silent_boot = false                 # Show boot progress for debugging

[display]
# Display settings optimized for gaming handhelds
auto_detect_display = true
preferred_resolution = "480x320"    # Common Anbernic resolution
fallback_resolution = "320x240"     # Safe fallback
refresh_rate = 60
color_depth = 16                    # 16-bit for performance
overscan_compensation = false       # Not needed on built-in screens

# Anbernic display specific settings
[display.anbernic]
built_in_screen = true              # Using built-in LCD
screen_size_inches = 3.5            # Default screen size
pixel_perfect_scaling = true        # Maintain aspect ratios
shader_support = true               # Enable display shaders
brightness_levels = 10              # Number of brightness levels
auto_brightness = false             # Manual brightness control
sleep_timeout_minutes = 5           # Screen sleep timeout
backlight_control = "gpio"          # Backlight control method

# Model-specific display settings
[display.models]
rg351p_width = 480
rg351p_height = 320
rg351m_width = 640
rg351m_height = 480
rg552_width = 1920
rg552_height = 1152

[input]
# Gaming input optimizations
gaming_controls_priority = true     # Prioritize gaming controls
keyboard_layout = "gaming"          # Gaming-optimized layout
analog_deadzone = 0.15              # Analog stick deadzone
button_debounce_ms = 5              # Button debounce time
turbo_button_support = true         # Enable turbo buttons

# Anbernic gaming controls
[input.gaming]
dpad_enabled = true
analog_sticks = 2                   # Number of analog sticks
action_buttons = 6                  # A, B, X, Y, L, R
shoulder_buttons = 4                # L1, L2, R1, R2
start_select_buttons = true
hotkey_button = "select"            # Hotkey for special functions
volume_buttons = true               # Dedicated volume controls
brightness_buttons = true          # Dedicated brightness controls

# Button mapping for different Anbernic models
[input.button_mapping]
# Standard RetroPad mapping
button_a = "east"
button_b = "south"
button_x = "north"
button_y = "west"
button_l1 = "l1"
button_r1 = "r1"
button_l2 = "l2"
button_r2 = "r2"
button_start = "start"
button_select = "select"

[gaming]
# Gaming-specific features
enable_gaming_mode = true
controller_support = true
auto_detect_controllers = false     # Built-in controls
rumble_support = false              # Most handhelds don't have rumble
save_state_support = true           # Enable save states
screenshot_support = true           # Enable screenshots
video_recording = false             # Disable for performance
frame_limiting = true               # Limit FPS for battery life
vsync = true                        # Enable V-Sync

# Gaming performance settings
[gaming.performance]
cpu_performance_mode = "balanced"   # battery, balanced, performance
gpu_performance_mode = "balanced"   # battery, balanced, performance
ram_optimization = true             # Optimize RAM usage
storage_optimization = true         # Optimize storage access
thermal_management = "aggressive"   # Prevent overheating
frame_skip = "auto"                 # Auto frame skip when needed

[audio]
# Audio settings for gaming handhelds
enable_audio = true
default_volume = 70                 # Default volume percentage
audio_driver = "alsa"               # Audio driver
sample_rate = 44100                 # Audio sample rate
buffer_size = 512                   # Audio buffer size
channels = 2                        # Stereo audio

# Gaming audio optimizations
[audio.gaming]
low_latency_audio = true            # Reduce audio latency
audio_resampling = "linear"         # Audio resampling quality
enable_audio_filters = false       # Disable for performance
headphone_detection = true          # Auto-switch to headphones
speaker_boost = false               # Boost internal speakers

[battery]
# Battery management for gaming handhelds
enable_battery_monitoring = true
battery_warning_level = 15          # Warning at 15%
battery_critical_level = 5          # Critical at 5%
auto_save_on_low_battery = true     # Auto-save game progress
suspend_on_critical_battery = true  # Auto-suspend at critical level
battery_saver_mode = true           # Enable battery saver features

# Power management
[battery.power_management]
cpu_scaling_on_battery = true       # Scale CPU based on battery
reduce_brightness_on_low = true     # Auto-reduce brightness
disable_wifi_on_critical = false    # Keep WiFi for emergency access
performance_mode_on_charger = true  # High performance when plugged in
sleep_timeout_on_battery = 300      # 5 minutes sleep timeout
hibernate_timeout_on_battery = 1800 # 30 minutes hibernate timeout

[storage]
# Storage optimization for gaming
auto_expand_filesystem = true
enable_trim = false                 # Usually not needed on SD cards
storage_monitoring = true
rom_storage_path = "/roms"          # ROM storage location
save_storage_path = "/saves"        # Save file location
screenshot_storage_path = "/screenshots" # Screenshot location

# Gaming storage optimization
[storage.gaming]
compress_saves = true               # Compress save files
auto_cleanup_temp = true            # Clean temporary files
cache_roms = false                  # Don't cache ROMs (save space)
compress_screenshots = true         # Compress screenshots
max_save_states = 10                # Limit save states per game

[emulation]
# Emulation-specific settings for gaming handhelds
enable_emulation_cores = true
retroarch_integration = true        # RetroArch integration
auto_detect_roms = true             # Auto-detect ROM files
rom_scanning = true                 # Scan for ROMs on boot
playlist_generation = true          # Generate game playlists

# Performance optimization for emulation
[emulation.performance]
rewind_support = false              # Disable rewind to save resources
shaders = false                     # Disable shaders for performance
runahead = false                    # Disable runahead for battery
threaded_video = false              # Disable for stability
sync_to_exact_content_framerate = true
vrr_runloop_enable = false

[security]
# Security settings for gaming handhelds
enable_ssh = false                  # Disable SSH by default
enable_firewall = true
web_interface_auth = false          # No auth needed for personal device
restrict_web_access = false         # Allow full web access
enable_parental_controls = false    # Gaming device specific

[monitoring]
# System monitoring optimized for gaming
enable_temperature_monitoring = true
temperature_warning_threshold = 60.0    # Lower threshold for handhelds
temperature_critical_threshold = 70.0   # Critical threshold
enable_performance_monitoring = true
fps_monitoring = true               # Monitor game FPS
battery_monitoring_interval = 30    # Check battery every 30 seconds
log_interval_seconds = 60           # Less frequent logging

[themes]
# UI themes for gaming handhelds
default_theme = "gaming_dark"       # Dark theme for OLED screens
enable_custom_themes = true
theme_path = "/themes"
auto_theme_switching = false        # Manual theme selection
high_contrast_mode = false

[localization]
# Localization for gaming interface
language = "ar"                     # Arabic interface
timezone = "Asia/Riyadh"
date_format = "dd/mm/yyyy"
time_format = "24h"
gaming_interface_language = "en"    # Keep gaming terms in English

[experimental]
# Experimental gaming features
enable_experimental_features = false
overclock_support = false           # Dangerous on handhelds
custom_bootloaders = false
advanced_power_management = false
beta_emulation_cores = false

# Device-specific optimizations for different Anbernic models
[models]

[models.rg351p]
display_width = 480
display_height = 320
cpu_max_freq = 1500000             # 1.5 GHz max
gpu_max_freq = 600000              # 600 MHz max
battery_capacity = 3500            # 3500 mAh
charging_current = 2000            # 2A charging

[models.rg351m]
display_width = 640
display_height = 480
cpu_max_freq = 1500000
gpu_max_freq = 600000
battery_capacity = 3500
charging_current = 2000

[models.rg351v]
display_width = 640
display_height = 480
cpu_max_freq = 1500000
gpu_max_freq = 600000
battery_capacity = 3500
charging_current = 2000
flip_screen = true                 # Vertical orientation

[models.rg552]
display_width = 1920
display_height = 1152
cpu_max_freq = 1800000             # 1.8 GHz max
gpu_max_freq = 800000              # 800 MHz max
battery_capacity = 6000            # 6000 mAh
charging_current = 3000            # 3A charging
wifi_5ghz_support = true           # 5 GHz WiFi support

[models.rg35xx]
display_width = 640
display_height = 480
cpu_max_freq = 1200000             # 1.2 GHz max
gpu_max_freq = 500000              # 500 MHz max
battery_capacity = 2400            # 2400 mAh
charging_current = 1500            # 1.5A charging
compact_mode = true                # Smaller device optimizations

# Custom gaming profiles
[gaming_profiles]

[gaming_profiles.battery_saver]
cpu_governor = "powersave"
gpu_performance = "low"
screen_brightness = 40
wifi_power_save = true
frame_limit = 30

[gaming_profiles.balanced]
cpu_governor = "ondemand"
gpu_performance = "balanced"
screen_brightness = 70
wifi_power_save = true
frame_limit = 60

[gaming_profiles.performance]
cpu_governor = "performance"
gpu_performance = "high"
screen_brightness = 90
wifi_power_save = false
frame_limit = 60

# Backup and recovery for gaming saves
[backup]
enable_auto_backup = true
backup_saves_only = true            # Only backup save files
backup_interval_hours = 6           # Backup every 6 hours
backup_location = "/backup"
max_backups = 20                    # Keep more backups for saves
compress_backups = true
cloud_backup_enabled = false       # No cloud backup by default

# Gaming-specific logging
[logging]
log_to_file = true
log_file_path = "/var/log/dos_safar_gaming.log"
max_log_size_mb = 5                 # Smaller log files
log_rotation_count = 3
console_log_level = "warn"          # Less console spam during gaming
file_log_level = "info"
log_gaming_events = true            # Log game launches, etc.
log_performance_metrics = true      # Log FPS, temperatures, etc.