# DOS Safar Enhanced Configuration
# Universal ARM Boot Manager for gaming handhelds and Raspberry Pi

[system]
device_type = "auto"  # auto, raspberry-pi, anbernic, orange-pi, etc.
log_level = "info"    # error, warn, info, debug, trace
config_persist_path = "/boot/dos_safar/"

[hardware]
test_timeout_seconds = 30
display_test_enabled = true
input_test_enabled = true
network_test_enabled = true
auto_save_working_config = true

[network]
# Primary WiFi settings (Pre-configured)
wifi_ssid = "YourHomeWiFi"          # ← ضع اسم الشبكة هنا
wifi_password = "YourWiFiPassword"   # ← ضع كلمة المرور هنا
connection_timeout_seconds = 3
auto_connect = true
ethernet_preferred = false

# Backup WiFi networks (for fallback)
backup_networks = [
    { ssid = "YourPhoneHotspot", password = "hotspot123" },
    { ssid = "GuestWiFi", password = "" },  # Open network
    { ssid = "WorkWiFi", password = "work2024" }
]

# Network behavior
auto_scan_open_networks = true      # البحث عن شبكات مفتوحة إذا فشل الاتصال
prefer_saved_networks = true        # إعطاء أولوية للشبكات المحفوظة
max_connection_attempts = 3         # محاولات الاتصال قبل الانتقال للبديل

[web]
port = 8080
host = "0.0.0.0"
enable_cors = true
static_files_path = "assets/web"
# Auto-launch web interface after network connection
auto_launch_interface = true       # فتح الواجهة تلقائياً بعد الاتصال
show_qr_code = true               # عرض QR Code للوصول السريع

[boot]
menu_timeout_seconds = 3          # ← 3 ثوان فقط
default_os = ""                   # Empty means auto-connect to web
show_advanced_options = false
gaming_mode = true
# Enhanced behavior
auto_web_on_timeout = true        # الاتصال بالويب إذا لم يتم الضغط على شيء
keyboard_interrupt_enabled = true # أي ضغطة توقف العملية التلقائية
show_ip_on_screen = true         # عرض IP address على الشاشة